// Low-frequency stability sentinel. The solver's rho field is already the
// cheapest complete diagnostic: any NaN generated by f propagates into rho.
// WGSL has no isFinite(), so NaN is detected by self-inequality; the large
// magnitude check also catches infinities/overflow. Integer atomics are safe
// here (the no-atomics rule applies specifically to f32 force reduction).

// Params is concatenated before this source.
@group(0) @binding(0) var<uniform> params: Params;
@group(0) @binding(1) var<storage, read> rho_in: array<f32>;
@group(0) @binding(2) var<storage, read_write> nan_flag: atomic<u32>;

@compute @workgroup_size(256)
fn nan_sentinel(@builtin(global_invocation_id) gid: vec3<u32>) {
  let cell = gid.x;
  if (cell >= params.nx * params.ny) {
    return;
  }
  let rho = rho_in[cell];
  if (!(rho == rho) || abs(rho) > 1e6) {
    atomicStore(&nan_flag, 1u);
  }
}
